### ISSUE TITLE
Add scratchcard.io / scratchcard to the title of the webapp

### ISSUE THREAD

**Issue by maxmeyer** [ahhbristow/index_cards#7]
If one adds it to the bookmarks, the browser reuses the current title which is "Three amigos". Finding your webapp in the bookmarks will be difficult then.

**Comment by ahhbristow** [comment]
That's interesting, I changed the title recently (ie, a few days ago) and it shows as "Scratchcard" for me.  You got a cached version of the page or something?

**Comment by maxmeyer** [comment]
No, I don't think so. I tried it on a different browser. Maybe Javascript? First you see the title as you mentioned it, but this is  changed after a couple of seconds.

**Comment by ahhbristow** [comment]
Try now.  I'd not updated the metadata on the login page (this needs refactoring so that it uses Angular as well instead of a full page load - there's an index.ejs and login.ejs template at the moment.  It should just be index.ejs).

**Comment by maxmeyer** [comment]
@ahhbristow Now it works. Thanks!
